name: CI/CD Pipeline

on: push

env:
  APPLICATION_NAME: app3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v3
      - name: run the script
        run: python app3.py
  
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: create the artifcat
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APPLICATION_NAME }}
          path: ./app3.py